name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o goderby.exe cmd/main.go
    
    - name: Build for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o goderby-darwin-amd64 cmd/main.go
    
    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o goderby-linux-amd64 cmd/main.go
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          goderby.exe
          goderby-darwin-amd64
          goderby-linux-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
